import WineImage from "@/images/wine.png";
import Bartolo from "@/images/barolo.png";
import Chardonnay from "@/images/BC-Chardonnay.png";
import CabernetSauvignon from "@/images/Cabernet-Sauvignon-Free-PNG.png";
import Syrah from "@/images/MauiWine-Syrah.png";
import RedWine from "@/images/red-wine.png";
import SauvignonBlanc from "@/images/Sauvignon blanc.png";

import SampleUser from "@/images/user-placeholder.jpg";
import LevelOne from "@/images/wine_1.png";
import LevelTwo from "@/images/wine_2.png";
import LevelThree from "@/images/wine_3.png";
import LevelFour from "@/images/wine_4.png";
import LevelFive from "@/images/wine_5.png";

import header1 from "@/images/header-wine/header1.png";
import header2 from "@/images/header-wine/header2.png";
import header3 from "@/images/header-wine/header3.png";
import header4 from "@/images/header-wine/header4.png";
import header5 from "@/images/header-wine/header5.png";
import header6 from "@/images/header-wine/header6.png";
import header7 from "@/images/header-wine/header7.png";
import header8 from "@/images/header-wine/header8.png";
import header9 from "@/images/header-wine/header9.png";
import header10 from "@/images/header-wine/header10.png";
import post1 from "@/images/post-wine/post1.jpg";
import post2 from "@/images/post-wine/post2.jpg";
import post3 from "@/images/post-wine/post3.jpg";
import post4 from "@/images/post-wine/post4.jpg";
import post5 from "@/images/post-wine/post5.jpg";
import post6 from "@/images/post-wine/post6.jpg";
import post7 from "@/images/post-wine/post7.jpg";
import post8 from "@/images/post-wine/post8.jpg";
import post9 from "@/images/post-wine/post9.jpg";
import post10 from "@/images/post-wine/post10.jpg";

import rp_score from "@/icons/rp_score.png";
import drinking_win from "@/icons/drinking_window.png";
import reviewed_by from "@/icons/reviewed_by.png";
import review_date from "@/icons/review_date.png";
import Image from "next/image";
import React from "react";

import DashboardHeader from "@/components/dashboard/dashboard-header";

export type HeaderContentItem = {
  title: string;
  content: JSX.Element; // Expecting JSX.Element here, not the type
};

export const BudgetData = [
  {
    label: "1 - 10k",
    budget: 10000,
  },
  {
    label: "10k - 50k",
    budget: 50000,
  },
  {
    label: "50k - 100k",
    budget: 100000,
  },
  {
    label: "100k+",
    budget: 100001,
  },
];

export const cases = [
  {
    value: 1,
    label: "1x75cl",
  },
  {
    value: 3,
    label: "3x75cl",
  },
  {
    value: 6,
    label: "6x75cl",
  },
  {
    value: 12,
    label: "12x75cl",
  },
];

export const InvestmentYearData = [
  {
    investment: "1 - 2 years",
  },
  {
    investment: "2 - 5 years",
  },
  {
    investment: "5 - 10 years",
  },
  {
    investment: "10+ years",
  },
];

export const InvestorData = [
  {
    boolean: true,
  },
  {
    boolean: false,
  },
];

export const MockNotifications = [
  {
    id: "10135442012",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    title: "LWIN: 1504500 negotiated to £450",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: (() => {
      const date = new Date();
      date.setDate(date.getDate() - 1); // 1 day ago
      return date;
    })(),

    responded: true,
  },
  {
    id: "10135442013",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    title: "New wine LWIN: 10101 on Market",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: (() => {
      const date = new Date();
      date.setDate(date.getDate() - 2); // 2 days ago
      return date;
    })(),
    responded: false,
  },
  {
    id: "10135442014",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    title: "New wine LWIN: 10101 on Market",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: (() => {
      const date = new Date();
      date.setDate(date.getDate() - 3); // 3 days ago
      return date;
    })(),
    responded: false,
  },
  {
    id: "10135442015",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    title: "New wine LWIN: 10101 on Market",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: (() => {
      const date = new Date();
      date.setDate(date.getDate() - 8); // 8 days ago
      return date;
    })(),
    responded: false,
  },
  {
    id: "10135442016",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    title: "New wine LWIN: 10101 on Market",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: (() => {
      const date = new Date();
      date.setDate(date.getDate() - 9); // 9 days ago
      return date;
    })(),
    responded: false,
  },
  {
    id: "10135442017",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    title: "Requested booking new date ",
    desc: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
    date: (() => {
      const date = new Date();
      date.setDate(date.getDate() - 10); // 10 days ago
      return date;
    })(),
    responded: true,
  },
];

export const MockSubAccounts = [
  {
    image: SampleUser,
    name: "Maxton Keller",
    contact_number: "+10100 - 101105",
    email: "john@gmail.com",
    status: "Magnum",
    investment: 8505,
    profit: 5100,
    id: "A98DB973KW1",
  },
  {
    image: SampleUser,
    name: "Krew Person",
    contact_number: "+10100 - 101105",
    email: "john@gmail.com",
    status: "Magnum",
    investment: 8505,
    profit: 5100,
    id: "A98DB973KW2",
  },
  {
    image: SampleUser,
    name: "Paula Hayes",
    contact_number: "+10100 - 101105",
    email: "john@gmail.com",
    status: "Magnum",
    investment: 8505,
    profit: 5100,
    id: "A98DB973KW3",
  },
  {
    image: SampleUser,
    name: "John Wick",
    contact_number: "+10100 - 101105",
    email: "john@gmail.com",
    status: "Magnum",
    investment: 8505,
    profit: 5100,
    id: "A98DB973KW4",
  },
];

export const MockActivites = [
  {
    activity: "Sell the 10062052020 Wine",
    status: "Pending",
    date: new Date().getDate(),
  },
];

export const BillingHistory = [
  {
    lwin: "10062052020",
    card_end: "2046",
    type: "Master Card",
    amount: 100,
    time_stamp: new Date().getDate(),
  },
  {
    lwin: "10062052020",
    card_end: "2046",
    type: "Master Card",
    amount: 100,
    time_stamp: new Date().getDate(),
  },
  {
    lwin: "10062052020",
    card_end: "2046",
    type: "Master Card",
    amount: 100,
    time_stamp: new Date().getDate(),
  },
  {
    lwin: "10062052020",
    card_end: "2046",
    type: "Master Card",
    amount: 100,
    time_stamp: new Date().getDate(),
  },
  {
    lwin: "10062052020",
    card_end: "2046",
    type: "Master Card",
    amount: 100,
    time_stamp: new Date().getDate(),
  },
  {
    lwin: "10062052020",
    card_end: "2046",
    type: "Master Card",
    amount: 100,
    time_stamp: new Date().getDate(),
  },
];

export const MockWines = [
  {
    id: "10135442011",
    sale: 20,
    price: 3286.52,
    description:
      "Oddly enough, from magnum, the 2000 Barolo is magnificent, with none of the imperfections I have found in so many of my bottles. The wine shows considerable 2000 personality in its warm, radiant fruit and sensual personality, but the large format has maintained freshness and verve. Readers who can find the 2000 in magnum will want to consider the wine Anticipated maturity: 2012-2025. After many years I have finally concluded that Bartolo Mascarello’s 2000 Barolo will always remain a mystery to me.",
    image: Bartolo,
    growth: 10,
    type: "Rare",
    status: "Pending",
    invested: 3286.52,
    name: "Barolo",
    full_name: "Bartolo Mascarello, Barolo",
    market_value: 2800.91,
    score: 93,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 5,
    from: "Barolo, Italy",
    alcohol_abv: "13.5%",
    blend: "100% Nebbiolo",
    grapes: "Nebbiolo",
    maturation: "Oaked",
    ownership: "Maria-Teresa Mascarello",
    vintage: "2000",
    num_cases: 1,
    gain_loss_percent: -4,
    gain_loss: 400,
  },
  {
    id: "10135442012",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: Chardonnay,
    growth: 10,
    type: "Rare",
    status: "--",
    invested: 1286.52,
    name: "Chardonnay",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 4,
    from: "Bordeaux, France",
    alcohol_abv: "13.5%",
    blend: "Cabernet Sauvignon",
    grapes: "Cabernet Sauvignon, Merlot",
    maturation: "Barrel-aged",
    ownership: "Château Margaux",
    vintage: "2016",
    num_cases: 2,
    gain_loss_percent: -7,
    gain_loss: 300,
  },
  {
    id: "10135442013",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: CabernetSauvignon,
    status: "--",
    invested: 2286.52,
    growth: 10,
    type: "Rare",
    name: "Cabernet Sauvignon",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 4,
    from: "Napa Valley, USA",
    alcohol_abv: "14.8%",
    blend: "Cabernet Sauvignon",
    grapes: "Cabernet Sauvignon",
    maturation: "Oaked",
    ownership: "Robert Mondavi Winery",
    vintage: "2017",
    num_cases: 3,
    gain_loss_percent: 2,
    gain_loss: 200,
  },
  {
    id: "10135442014",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: Syrah,
    growth: 10,
    type: "Rare",
    status: "Pending",
    invested: 3686.52,
    name: "Syrah",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 4.5,
    from: "Rioja, Spain",
    alcohol_abv: "14%",
    blend: "Tempranillo",
    grapes: "Tempranillo",
    maturation: "American Oak",
    ownership: "Marqués de Riscal",
    vintage: "2018",
    num_cases: 1,
    gain_loss_percent: -1,
    gain_loss: 100,
  },
  {
    id: "10135442015",
    sale: 20,
    price: 3286.52,
    description:
      "Red Wine kini Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: RedWine,
    growth: 10,
    status: "Pending",
    invested: 1216.52,
    type: "Rare",
    name: "Red Wine",
    full_name: "Red Wine",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 5,
    from: "Barossa Valley, Australia",
    alcohol_abv: "15%",
    blend: "Shiraz",
    grapes: "Shiraz",
    maturation: "French Oak",
    ownership: "Penfolds",
    vintage: "2019",
    num_cases: 2,
    gain_loss_percent: 1,
    gain_loss: 100,
  },
  {
    id: "10135442016",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: SauvignonBlanc,
    growth: 10,
    status: "--",
    invested: 1786.52,
    type: "Rare",
    name: "Sauvignon blanc",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 5,
    from: "Chianti Classico, Italy",
    alcohol_abv: "13%",
    blend: "Sangiovese",
    grapes: "Sangiovese",
    maturation: "Oaked",
    ownership: "Antinori Family",
    vintage: "2020",
    num_cases: 3,
    gain_loss_percent: 2,
    gain_loss: 200,
  },
  {
    id: "10135442017",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    growth: 10,
    status: "Pending",
    invested: 3386.52,
    type: "Rare",
    name: "Chateau Mouton Rothschild",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 5,
    from: "Mendoza, Argentina",
    alcohol_abv: "14.5%",
    blend: "Malbec",
    grapes: "Malbec",
    maturation: "French Oak",
    ownership: "Catena Zapata",
    vintage: "2021",
    num_cases: 3,
    gain_loss_percent: 7,
    gain_loss: 700,
  },
  {
    id: "10135442018",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    growth: 10,
    status: "Pending",
    invested: 3766.52,
    type: "Rare",
    name: "Chateau Mouton Rothschild",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 4.5,
    from: "Champagne, France",
    alcohol_abv: "12%",
    blend: "Pinot Noir, Chardonnay",
    grapes: "Pinot Noir, Chardonnay",
    maturation: "Bottle-aged",
    ownership: "Moët & Chandon",
    vintage: "2022",
    num_cases: 1,
    gain_loss_percent: 2,
    gain_loss: 200,
  },
];

export const MockWinesFromBuilder = [
  {
    id: "10135442015",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    growth: 10,
    type: "Rare",
    status: "--",
    invested: 3766.52,
    name: "Chateau Mouton Rothschild",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 5,
    from: "Toscana IGT, Italy",
    alcohol_abv: "15%",
    blend: "Merlot",
    grapes: "Merlot",
    maturation: "Oaked",
    ownership: "Frescobaldi Family",
    vintage: "2022",
    num_cases: 1,
    gain_loss_percent: 2,
    gain_loss: 200,
  },
  {
    id: "10135442015",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    growth: 10,
    type: "Rare",
    status: "Pending",
    invested: 4566.52,
    name: "Chateau Mouton Rothschild",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 4,
    from: "Toscana IGT, Italy",
    alcohol_abv: "15%",
    blend: "Merlot",
    grapes: "Merlot",
    maturation: "Oaked",
    ownership: "Frescobaldi Family",
    vintage: "2022",
    num_cases: 1,
    gain_loss_percent: 2,
    gain_loss: 200,
  },
  {
    id: "10135442015",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    growth: 10,
    type: "Rare",
    status: "--",
    invested: 1766.52,
    name: "Chateau Mouton Rothschild",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 4,
    from: "Toscana IGT, Italy",
    alcohol_abv: "15%",
    blend: "Merlot",
    grapes: "Merlot",
    maturation: "Oaked",
    ownership: "Frescobaldi Family",
    vintage: "2022",
    num_cases: 1,
    gain_loss_percent: 2,
    gain_loss: 200,
  },
  {
    id: "10135442015",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    growth: 10,
    type: "Rare",
    status: "Pending",
    invested: 1721.52,
    name: "Chateau Mouton Rothschild",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 4.5,
    from: "Toscana IGT, Italy",
    alcohol_abv: "15%",
    blend: "Merlot",
    grapes: "Merlot",
    maturation: "Oaked",
    ownership: "Frescobaldi Family",
    vintage: "2022",
    num_cases: 1,
    gain_loss_percent: 2,
    gain_loss: 200,
  },
  {
    id: "10135442015",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    growth: 10,
    type: "Rare",
    status: "Pending",
    invested: 2266.52,
    name: "Chateau Mouton Rothschild",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 5,
    from: "Toscana IGT, Italy",
    alcohol_abv: "15%",
    blend: "Merlot",
    grapes: "Merlot",
    maturation: "Oaked",
    ownership: "Frescobaldi Family",
    vintage: "2022",
    num_cases: 1,
    gain_loss_percent: 2,
    gain_loss: 200,
  },
  {
    id: "10135442015",
    sale: 20,
    price: 3286.52,
    description:
      "Lorem  ipsum odor amet, consectetuer adipiscing elit. Per vestibulum commodo sit donec non tellus vel. Aptent et mauris ac potenti, ridiculus natoque. Venenatis vestibulum maximus duis facilisi nec dictumst. Ac sociosqu suscipit molestie urna adipiscing per. Egestas vehicula class velit vulputate tempor adipiscing? Malesuada velit tempor praesent hendrerit tellus luctus auctor purus.",
    image: WineImage,
    growth: 10,
    type: "Rare",
    status: "Pending",
    invested: 3799.52,
    name: "Chateau Mouton Rothschild",
    full_name: "Chateau Lafite Rothschild Premier Cru Classe, Pauillac",
    market_value: 2800.91,
    score: 98,
    case_size: "1x75",
    recommended_holding: "2yrs",
    stars: 5,
    from: "Toscana IGT, Italy",
    alcohol_abv: "15%",
    blend: "Merlot",
    grapes: "Merlot",
    maturation: "Oaked",
    ownership: "Frescobaldi Family",
    vintage: "2022",
    num_cases: 1,
    gain_loss_percent: 2,
    gain_loss: 200,
  },
];

export const MockChartData = [
  { date: "2024-01-01", category_a: 222, category_b: 150 },
  { date: "2024-02-01", category_a: 397, category_b: 280 },
  { date: "2024-03-01", category_a: 467, category_b: 320 },
  { date: "2024-04-01", category_a: 542, category_b: 460 },
  { date: "2024-05-01", category_a: 673, category_b: 590 },
  { date: "2024-06-01", category_a: 701, category_b: 640 },
  { date: "2024-07-01", category_a: 845, category_b: 880 },
  { date: "2024-08-01", category_a: 909, category_b: 920 },
  { date: "2024-09-01", category_a: 1009, category_b: 1010 },
  { date: "2024-10-11", category_a: 1161, category_b: 1190 },
  { date: "2024-11-11", category_a: 1227, category_b: 1350 },
  { date: "2024-12-11", category_a: 1332, category_b: 1410 },
];

export const MockProfileLevelData = [
  {
    percentage: "2.75% fee",
    level: LevelOne,
    name: "VINTAGE",
    liters: "0.2 Liters",
    price: "£25,000 - £250,000 investor",
    hoverFrom: "#70A1A3",
    hoverTo: "#145356",
    display: "content",
    check: "content",
  },
  {
    percentage: "2.5% fee",
    level: LevelTwo,
    name: "VINTAGE CRU",
    liters: "2.5 Liters",
    price: "£250,000 - £500,000 investor",
    hoverFrom: "#C0392B",
    hoverTo: "#8D1B22",
    display: "content",
    check: "none",
  },
  {
    percentage: "2.25% fee",
    level: LevelThree,
    liters: "1.5 Liters",
    name: "VINTAGE VAULT",
    price: "£500,000 - £1M investor",
    hoverFrom: "#CE919B",
    hoverTo: "#AC00F3",
    display: "content",
    check: "none",
  },
  {
    percentage: "2% fee",
    level: LevelFour,
    name: "VINTAGE ENCLOSURE",
    liters: "4.5 Liters",
    price: "£1M - £2.5m investor",
    hoverFrom: "#A8927A",
    hoverTo: "#DDC4A9",
    display: "content",
    check: "none",
  },
  {
    percentage: "1.85% fee",
    level: LevelFive,
    name: "VINTAGE ASSOCIATE",
    liters: "6 Liters",
    price: "£2.5M + Investor",
    hoverFrom: "#2A2C2D",
    hoverTo: "#2A2C2D",
    display: "none",
    check: "none",
  },
];

export const MockProfileTableData = [
  {
    picture: "https://i.imgur.com/geyZWec.png",
    name: "Chateau Mouton Rothschild",
    market_value: 3586.52,
    invested: 3286.52,
    price: 2286.52,
    case_size: "1x75",
    status: "Pending",
    type: "Rare",
  },
  {
    picture: "https://i.imgur.com/geyZWec.png",
    name: "Chateau Mouton Rothschild",
    market_value: 419.0,
    price: 2286.52,
    invested: 3286.52,
    case_size: "1x75",
    status: "--",
    type: "Rare",
  },
  {
    picture: "https://i.imgur.com/geyZWec.png",
    name: "Chateau Mouton Rothschild",
    market_value: 3586.52,
    price: 2286.52,
    invested: 3286.52,
    case_size: "1x75",
    status: "Pending",
    type: "Rare",
  },
  {
    picture: "https://i.imgur.com/geyZWec.png",
    name: "Chateau Mouton Rothschild",
    market_value: 419.0,
    price: 2286.52,
    invested: 3286.52,
    case_size: "1x75",
    status: "--",
    type: "Rare",
  },
  {
    picture: "https://i.imgur.com/geyZWec.png",
    name: "Chateau Mouton Rothschild",
    price: 3586.52,
    market_value: 3586.52,
    invested: 3286.52,
    case_size: "1x75",
    status: "Pending",
    type: "Rare",
  },
  {
    picture: "https://i.imgur.com/geyZWec.png",
    name: "Chateau Mouton Rothschild",
    market_value: 419.0,
    price: 2286.52,
    invested: 3286.52,
    case_size: "1x75",
    status: "--",
    type: "Rare",
  },
];

export const chartData = [
  { month: "January", desktop: 186 },
  { month: "February", desktop: 282 },
  { month: "March", desktop: 184 },
  { month: "April", desktop: 281 },
  { month: "May", desktop: 487 },
  { month: "June", desktop: 386 },
  { month: "July", desktop: 482 },
  { month: "August", desktop: 454 },
  { month: "September", desktop: 381 },
  { month: "October", desktop: 587 },
  { month: "November", desktop: 485 },
  { month: "December", desktop: 382 },
  { month: "January", desktop: 234 },
  { month: "February", desktop: 356 },
  { month: "March", desktop: 287 },
  { month: "April", desktop: 172 },
  { month: "May", desktop: 493 },
  { month: "June", desktop: 402 },
  { month: "July", desktop: 478 },
  { month: "August", desktop: 439 },
  { month: "September", desktop: 390 },
  { month: "October", desktop: 560 },
  { month: "November", desktop: 457 },
  { month: "December", desktop: 374 },
  { month: "January", desktop: 201 },
  { month: "February", desktop: 288 },
  { month: "March", desktop: 179 },
  { month: "April", desktop: 285 },
  { month: "May", desktop: 489 },
  { month: "June", desktop: 417 },
  { month: "July", desktop: 298 },
  { month: "August", desktop: 372 },
  { month: "September", desktop: 435 },
  { month: "October", desktop: 512 },
  { month: "November", desktop: 420 },
  { month: "December", desktop: 362 },
  { month: "January", desktop: 477 },
  { month: "February", desktop: 339 },
  { month: "March", desktop: 256 },
  { month: "April", desktop: 404 },
  { month: "May", desktop: 486 },
  { month: "June", desktop: 472 },
  { month: "July", desktop: 358 },
  { month: "August", desktop: 421 },
  { month: "September", desktop: 480 },
  { month: "October", desktop: 535 },
  { month: "November", desktop: 511 },
  { month: "December", desktop: 462 },
  { month: "January", desktop: 249 },
  { month: "February", desktop: 365 },
  { month: "March", desktop: 295 },
  { month: "April", desktop: 376 },
  { month: "May", desktop: 523 },
  { month: "June", desktop: 413 },
  { month: "July", desktop: 397 },
  { month: "August", desktop: 465 },
];

export const chartLegends = [
  {
    browser: "rest_of_world",
    label: "Rest of the World",
    color: "#8D1B22",
  },
  {
    browser: "united_kingdom",
    label: "UN",
    color: "#EC841A",
  },
  {
    browser: "bordeaux",
    label: "Bordeaux",
    color: "#104144",
  },
  {
    browser: "italy",
    label: "Italy",
    color: "#1BCD32",
  },
  {
    browser: "champagne",
    label: "Champagne",
    color: "#C4AD93",
  },
  {
    browser: "rhone",
    label: "Rhone",
    color: "#F7C143",
  },
  {
    browser: "burgundy",
    label: "Burgundy",
    color: "#121416",
  },
];

export const chartsData = [
  { browser: "rest_of_world", visitors: 275, fill: "#8D1B22" },
  { browser: "united_kingdom", visitors: 200, fill: "#EC841A" },
  { browser: "bordeaux", visitors: 287, fill: "#104144" },
  { browser: "italy", visitors: 173, fill: "#1BCD32" },
  { browser: "champagne", visitors: 190, fill: "#C4AD93" },
  { browser: "rhone", visitors: 190, fill: "#F7C143" },
  { browser: "burgundy", visitors: 190, fill: "#121416" },
];

export const depositData = [
  {
    label: "Type",
    value: "Organization",
  },
  {
    label: "Account Name",
    value: "Vintage Associates",
  },
  {
    label: "Account Number",
    value: "80597604645",
  },
  {
    label: "Your account ID",
    value: "3335645",
  },
];

export const wineDataIndicies = {
  "Liv-ex Fine Wine 50": [
    {
      year: "2024",
      Jan: 40,
      Feb: 55,
      Mar: 50,
      Apr: 60,
      May: 70,
      Jun: 65,
      Jul: 85,
      Aug: 90,
      Sep: 80,
      Oct: 95,
      Nov: 85,
      Dec: 100,
    },
    {
      year: "2023",
      Jan: 35,
      Feb: 50,
      Mar: 45,
      Apr: 60,
      May: 65,
      Jun: 70,
      Jul: 80,
      Aug: 75,
      Sep: 85,
      Oct: 90,
      Nov: 95,
      Dec: 100,
    },
    {
      year: "2022",
      Jan: 30,
      Feb: 45,
      Mar: 40,
      Apr: 55,
      May: 60,
      Jun: 55,
      Jul: 75,
      Aug: 70,
      Sep: 80,
      Oct: 85,
      Nov: 90,
      Dec: 95,
    },
    {
      year: "2021",
      Jan: 25,
      Feb: 40,
      Mar: 35,
      Apr: 50,
      May: 55,
      Jun: 60,
      Jul: 70,
      Aug: 65,
      Sep: 75,
      Oct: 80,
      Nov: 85,
      Dec: 90,
    },
    {
      year: "2020",
      Jan: 20,
      Feb: 35,
      Mar: 30,
      Apr: 45,
      May: 50,
      Jun: 45,
      Jul: 65,
      Aug: 60,
      Sep: 70,
      Oct: 75,
      Nov: 80,
      Dec: 85,
    },
  ],

  "California 50": [
    {
      year: "2024",
      Jan: 25,
      Feb: 45,
      Mar: 40,
      Apr: 50,
      May: 60,
      Jun: 55,
      Jul: 70,
      Aug: 75,
      Sep: 80,
      Oct: 90,
      Nov: 95,
      Dec: 85,
    },
    {
      year: "2023",
      Jan: 30,
      Feb: 50,
      Mar: 45,
      Apr: 55,
      May: 65,
      Jun: 75,
      Jul: 85,
      Aug: 80,
      Sep: 90,
      Oct: 100,
      Nov: 105,
      Dec: 95,
    },
    {
      year: "2022",
      Jan: 35,
      Feb: 55,
      Mar: 50,
      Apr: 60,
      May: 70,
      Jun: 80,
      Jul: 90,
      Aug: 85,
      Sep: 95,
      Oct: 105,
      Nov: 110,
      Dec: 100,
    },
    {
      year: "2021",
      Jan: 40,
      Feb: 60,
      Mar: 55,
      Apr: 65,
      May: 75,
      Jun: 85,
      Jul: 95,
      Aug: 90,
      Sep: 100,
      Oct: 110,
      Nov: 115,
      Dec: 105,
    },
    {
      year: "2020",
      Jan: 45,
      Feb: 65,
      Mar: 60,
      Apr: 70,
      May: 80,
      Jun: 90,
      Jul: 100,
      Aug: 95,
      Sep: 105,
      Oct: 115,
      Nov: 120,
      Dec: 110,
    },
  ],

  "Port 50": [
    {
      year: "2024",
      Jan: 30,
      Feb: 40,
      Mar: 50,
      Apr: 45,
      May: 55,
      Jun: 60,
      Jul: 65,
      Aug: 75,
      Sep: 85,
      Oct: 70,
      Nov: 90,
      Dec: 95,
    },
    {
      year: "2023",
      Jan: 35,
      Feb: 45,
      Mar: 55,
      Apr: 60,
      May: 70,
      Jun: 75,
      Jul: 80,
      Aug: 85,
      Sep: 90,
      Oct: 95,
      Nov: 100,
      Dec: 105,
    },
    {
      year: "2022",
      Jan: 40,
      Feb: 50,
      Mar: 60,
      Apr: 65,
      May: 75,
      Jun: 80,
      Jul: 85,
      Aug: 90,
      Sep: 95,
      Oct: 100,
      Nov: 105,
      Dec: 110,
    },
    {
      year: "2021",
      Jan: 45,
      Feb: 55,
      Mar: 65,
      Apr: 70,
      May: 80,
      Jun: 85,
      Jul: 90,
      Aug: 95,
      Sep: 100,
      Oct: 105,
      Nov: 110,
      Dec: 115,
    },
    {
      year: "2020",
      Jan: 50,
      Feb: 60,
      Mar: 70,
      Apr: 75,
      May: 85,
      Jun: 90,
      Jul: 95,
      Aug: 100,
      Sep: 105,
      Oct: 110,
      Nov: 115,
      Dec: 120,
    },
  ],

  "Burgundy 150": [
    {
      year: "2024",
      Jan: 55,
      Feb: 60,
      Mar: 65,
      Apr: 70,
      May: 75,
      Jun: 80,
      Jul: 90,
      Aug: 85,
      Sep: 95,
      Oct: 100,
      Nov: 105,
      Dec: 110,
    },
    {
      year: "2023",
      Jan: 60,
      Feb: 65,
      Mar: 70,
      Apr: 75,
      May: 85,
      Jun: 90,
      Jul: 95,
      Aug: 100,
      Sep: 105,
      Oct: 110,
      Nov: 115,
      Dec: 120,
    },
    {
      year: "2022",
      Jan: 65,
      Feb: 70,
      Mar: 75,
      Apr: 80,
      May: 90,
      Jun: 95,
      Jul: 100,
      Aug: 105,
      Sep: 110,
      Oct: 115,
      Nov: 120,
      Dec: 125,
    },
    {
      year: "2021",
      Jan: 70,
      Feb: 75,
      Mar: 80,
      Apr: 85,
      May: 95,
      Jun: 100,
      Jul: 105,
      Aug: 110,
      Sep: 115,
      Oct: 120,
      Nov: 125,
      Dec: 130,
    },
    {
      year: "2020",
      Jan: 75,
      Feb: 80,
      Mar: 85,
      Apr: 90,
      May: 100,
      Jun: 105,
      Jul: 110,
      Aug: 115,
      Sep: 120,
      Oct: 125,
      Nov: 130,
      Dec: 135,
    },
  ],

  "Champagne 50": [
    {
      year: "2024",
      Jan: 35,
      Feb: 45,
      Mar: 55,
      Apr: 50,
      May: 60,
      Jun: 70,
      Jul: 80,
      Aug: 90,
      Sep: 85,
      Oct: 95,
      Nov: 100,
      Dec: 110,
    },
    {
      year: "2023",
      Jan: 40,
      Feb: 50,
      Mar: 60,
      Apr: 65,
      May: 70,
      Jun: 75,
      Jul: 85,
      Aug: 90,
      Sep: 95,
      Oct: 100,
      Nov: 110,
      Dec: 115,
    },
    {
      year: "2022",
      Jan: 45,
      Feb: 55,
      Mar: 65,
      Apr: 70,
      May: 80,
      Jun: 85,
      Jul: 95,
      Aug: 100,
      Sep: 105,
      Oct: 110,
      Nov: 120,
      Dec: 125,
    },
    {
      year: "2021",
      Jan: 50,
      Feb: 60,
      Mar: 70,
      Apr: 75,
      May: 85,
      Jun: 90,
      Jul: 100,
      Aug: 105,
      Sep: 110,
      Oct: 115,
      Nov: 125,
      Dec: 130,
    },
    {
      year: "2020",
      Jan: 55,
      Feb: 65,
      Mar: 75,
      Apr: 80,
      May: 90,
      Jun: 95,
      Jul: 105,
      Aug: 110,
      Sep: 115,
      Oct: 120,
      Nov: 130,
      Dec: 135,
    },
  ],

  "Liv-ex Wine 50": [
    {
      year: "2024",
      Jan: 25,
      Feb: 35,
      Mar: 45,
      Apr: 50,
      May: 55,
      Jun: 65,
      Jul: 75,
      Aug: 80,
      Sep: 85,
      Oct: 90,
      Nov: 95,
      Dec: 100,
    },
    {
      year: "2023",
      Jan: 30,
      Feb: 40,
      Mar: 50,
      Apr: 55,
      May: 65,
      Jun: 75,
      Jul: 80,
      Aug: 85,
      Sep: 90,
      Oct: 100,
      Nov: 105,
      Dec: 110,
    },
    {
      year: "2022",
      Jan: 35,
      Feb: 45,
      Mar: 55,
      Apr: 60,
      May: 70,
      Jun: 80,
      Jul: 90,
      Aug: 95,
      Sep: 100,
      Oct: 110,
      Nov: 115,
      Dec: 120,
    },
    {
      year: "2021",
      Jan: 40,
      Feb: 50,
      Mar: 60,
      Apr: 65,
      May: 75,
      Jun: 85,
      Jul: 95,
      Aug: 100,
      Sep: 105,
      Oct: 115,
      Nov: 120,
      Dec: 125,
    },
    {
      year: "2020",
      Jan: 45,
      Feb: 55,
      Mar: 65,
      Apr: 70,
      May: 80,
      Jun: 90,
      Jul: 100,
      Aug: 105,
      Sep: 110,
      Oct: 120,
      Nov: 125,
      Dec: 130,
    },
  ],

  "Liv-ex Fine Wine 51": [
    {
      year: "2024",
      Jan: 40,
      Feb: 55,
      Mar: 50,
      Apr: 60,
      May: 70,
      Jun: 65,
      Jul: 85,
      Aug: 90,
      Sep: 80,
      Oct: 95,
      Nov: 85,
      Dec: 100,
    },
    {
      year: "2023",
      Jan: 35,
      Feb: 50,
      Mar: 45,
      Apr: 60,
      May: 65,
      Jun: 70,
      Jul: 80,
      Aug: 75,
      Sep: 85,
      Oct: 90,
      Nov: 95,
      Dec: 100,
    },
    {
      year: "2022",
      Jan: 30,
      Feb: 45,
      Mar: 40,
      Apr: 55,
      May: 60,
      Jun: 55,
      Jul: 75,
      Aug: 70,
      Sep: 80,
      Oct: 85,
      Nov: 90,
      Dec: 95,
    },
    {
      year: "2021",
      Jan: 25,
      Feb: 40,
      Mar: 35,
      Apr: 50,
      May: 55,
      Jun: 60,
      Jul: 70,
      Aug: 65,
      Sep: 75,
      Oct: 80,
      Nov: 85,
      Dec: 90,
    },
    {
      year: "2020",
      Jan: 20,
      Feb: 35,
      Mar: 30,
      Apr: 45,
      May: 50,
      Jun: 45,
      Jul: 65,
      Aug: 60,
      Sep: 70,
      Oct: 75,
      Nov: 80,
      Dec: 85,
    },
  ],

  "California 51": [
    {
      year: "2024",
      Jan: 25,
      Feb: 45,
      Mar: 40,
      Apr: 50,
      May: 60,
      Jun: 55,
      Jul: 70,
      Aug: 75,
      Sep: 80,
      Oct: 90,
      Nov: 95,
      Dec: 85,
    },
    {
      year: "2023",
      Jan: 30,
      Feb: 50,
      Mar: 45,
      Apr: 55,
      May: 65,
      Jun: 75,
      Jul: 85,
      Aug: 80,
      Sep: 90,
      Oct: 100,
      Nov: 105,
      Dec: 95,
    },
    {
      year: "2022",
      Jan: 35,
      Feb: 55,
      Mar: 50,
      Apr: 60,
      May: 70,
      Jun: 80,
      Jul: 90,
      Aug: 85,
      Sep: 95,
      Oct: 105,
      Nov: 110,
      Dec: 100,
    },
    {
      year: "2021",
      Jan: 40,
      Feb: 60,
      Mar: 55,
      Apr: 65,
      May: 75,
      Jun: 85,
      Jul: 95,
      Aug: 90,
      Sep: 100,
      Oct: 110,
      Nov: 115,
      Dec: 105,
    },
    {
      year: "2020",
      Jan: 45,
      Feb: 65,
      Mar: 60,
      Apr: 70,
      May: 80,
      Jun: 90,
      Jul: 100,
      Aug: 95,
      Sep: 105,
      Oct: 115,
      Nov: 120,
      Dec: 110,
    },
  ],

  "Port 51": [
    {
      year: "2024",
      Jan: 30,
      Feb: 40,
      Mar: 50,
      Apr: 45,
      May: 55,
      Jun: 60,
      Jul: 65,
      Aug: 75,
      Sep: 85,
      Oct: 70,
      Nov: 90,
      Dec: 95,
    },
    {
      year: "2023",
      Jan: 35,
      Feb: 45,
      Mar: 55,
      Apr: 60,
      May: 70,
      Jun: 75,
      Jul: 80,
      Aug: 85,
      Sep: 90,
      Oct: 95,
      Nov: 100,
      Dec: 105,
    },
    {
      year: "2022",
      Jan: 40,
      Feb: 50,
      Mar: 60,
      Apr: 65,
      May: 75,
      Jun: 80,
      Jul: 85,
      Aug: 90,
      Sep: 95,
      Oct: 100,
      Nov: 105,
      Dec: 110,
    },
    {
      year: "2021",
      Jan: 45,
      Feb: 55,
      Mar: 65,
      Apr: 70,
      May: 80,
      Jun: 85,
      Jul: 90,
      Aug: 95,
      Sep: 100,
      Oct: 105,
      Nov: 110,
      Dec: 115,
    },
    {
      year: "2020",
      Jan: 50,
      Feb: 60,
      Mar: 70,
      Apr: 75,
      May: 85,
      Jun: 90,
      Jul: 95,
      Aug: 100,
      Sep: 105,
      Oct: 110,
      Nov: 115,
      Dec: 120,
    },
  ],
};

export const PostMock = [
  {
    id: 1,
    title: "Exploring the Future of Technology",
    subtitle: "A deep dive into AI advancements",
    slug: "future-of-technology.jpg",
    publishedBy: "Tech Guru",
    publishedAt: "2024-12-21T09:30:00",
    coverImage: header1,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post1,
  },
  {
    id: 2,
    title: "The Art of Minimalist Design",
    subtitle: "Less is more in web design",
    slug: "minimalist-design.jpg",
    publishedBy: "Design Weekly",
    publishedAt: "2024-11-18T15:45:00",
    coverImage: header2,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post2,
  },
  {
    id: 3,
    title: "Understanding Quantum Computing",
    subtitle: "How it will change the world",
    slug: "quantum-computing.jpg",
    publishedBy: "Science Daily",
    publishedAt: "2024-12-10T11:20:00",
    coverImage: header3,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post3,
  },
  {
    id: 4,
    title: "The Rise of Electric Vehicles",
    subtitle: "What the future holds for EVs",
    slug: "electric-vehicles.jpg",
    publishedBy: "Green Tech",
    publishedAt: "2024-10-22T08:10:00",
    coverImage: header4,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post4,
  },
  {
    id: 5,
    title: "The Power of Renewable Energy",
    subtitle: "Solar, wind, and beyond",
    slug: "renewable-energy.jpg",
    publishedBy: "Eco Earth",
    publishedAt: "2024-11-30T10:00:00",
    coverImage: header5,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post5,
  },
  {
    id: 6,
    title: "Mastering the Art of Photography",
    subtitle: "Tips for capturing stunning photos",
    slug: "photography-tips.jpg",
    publishedBy: "Photo Pro",
    publishedAt: "2024-09-15T14:30:00",
    coverImage: header6,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post6,
  },
  {
    id: 7,
    title: "The Future of Space Exploration",
    subtitle: "Mars missions and beyond",
    slug: "space-exploration.jpg",
    publishedBy: "Space Enthusiast",
    publishedAt: "2024-12-05T09:00:00",
    coverImage: header7,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post7,
  },
  {
    id: 8,
    title: "The Psychology of Color in Marketing",
    subtitle: "How colors influence consumer behavior",
    slug: "color-psychology.jpg",
    publishedBy: "Marketing Minds",
    publishedAt: "2024-08-20T13:15:00",
    coverImage: header8,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post8,
  },
  {
    id: 9,
    title: "The Evolution of Mobile Gaming",
    subtitle: "From Snake to AR games",
    slug: "mobile-gaming.jpg",
    publishedBy: "Gamer's Hub",
    publishedAt: "2024-07-07T16:50:00",
    coverImage: header9,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post9,
  },
  {
    id: 10,
    title: "Breaking Down Blockchain Technology",
    subtitle: "A non-technical guide",
    slug: "blockchain-technology.jpg",
    publishedBy: "Tech World",
    publishedAt: "2024-06-12T12:00:00",
    coverImage: header10,
    description:
      "Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>As she sat watching the world go by, something caught her eye. It wasn't so much its color or shape, but the way it was moving. She squinted to see if she could better understand what it was and where it was going, but it didn't help. As she continued to stare into the distance, she didn't understand why this uneasiness was building inside her body. She felt like she should get up and run. If only she could make out what it was. At that moment, she comprehended what it was and where it was heading, and she knew her life would never be the same. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself. Don't forget that gifts often come with costs that go beyond their purchase price. When you purchase a child the latest smartphone, you're also committing to a monthly phone bill. When you purchase the latest gaming system, you're likely not going to be satisfied with the games that come with it for long and want to purchase new titles to play. When you buy gifts it's important to remember that some come with additional costs down the road that can be much more expensive than the initial gift itself.<br/><br/>Betty decided to write a short story and she was sure it was going to be amazing. She had already written it in her head and each time she thought about it she grinned from ear to ear knowing how wonderful it would be. She could imagine the accolades coming in and the praise she would receive for creating such a wonderful piece. She was therefore extremely frustrated when she actually sat down to write the short story and the story that was so beautiful inside her head refused to come out that way on paper.",
    postImage: post10,
  },
];

export const StatisticMock = [
  {
    icon: rp_score,
    title: "Lifetime Performance",
    subtitle: "100",
    color: "black",
  },
  {
    icon: drinking_win,
    title: "Drinking Window",
    subtitle: "2020 - 2022",
    color: "#45D658",
  },
  {
    icon: reviewed_by,
    title: "Reviewed by",
    subtitle: "Monica Larner",
    color: "black",
  },
  {
    icon: review_date,
    title: "Review date",
    subtitle: "April 19. 2019",
    color: "black",
  },
];
